# Generated by Django 5.1.1 on 2024-09-09 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Score",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("english", models.IntegerField()),
                ("math", models.IntegerField()),
                ("science", models.IntegerField()),
                ("exam_date", models.DateTimeField(null=True)),
                (
                    "student",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="study.student",
                    ),
                ),
            ],
        ),
    ]
