# Generated by Django 5.1.1 on 2024-09-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("study", "0002_score"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
